jobs:
  build:
    docker:
      - image: cimg/base:2022.09
    steps:
      - checkout
      # Whatever you want to do
      - run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - run: az login -u ramakrishna.diddele@thinkartha.com -p Bani.d@1234
      - run: sudo apt update && sudo apt install software-properties-common gnupg2 curl && curl https://apt.releases.hashicorp.com/gpg | gpg --dearmor > hashicorp.gpg && sudo install -o root -g root -m 644 hashicorp.gpg /etc/apt/trusted.gpg.d/
      - run: sudo apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main" && sudo apt update && sudo apt install terraform
      - run: git clone https://github.com/subhransu-1/today2.git &&  cd today2 && terraform init && terraform validate && terraform fmt && terraform apply && terraform destroy
